"use client";

import { parseInvoiceDocument, type InvoiceImportDraft } from "@/application/services/invoice-import";
import { exportInvoicePdf } from "@/application/services/document-export";
import type { Invoice, Project } from "@/domain/entities/business";
import { routes } from "@/lib/routes";
import { EmptyTableRow, PageHeader, StatusBadge } from "@/presentation/components/ui";
import { money } from "@/presentation/data/sample-data";
import { InvoiceDocumentModal } from "@/presentation/features/invoices/invoice-document-modal";
import { useBusinessData } from "@/presentation/providers/business-data-provider";
import { Download, Edit3, FileUp, LoaderCircle, Plus, Search } from "lucide-react";
import Link from "next/link";
import { useRef, useState, type ReactNode } from "react";

function Toolbar({query,onQuery,placeholder,children}:{query:string;onQuery:(value:string)=>void;placeholder:string;children?:ReactNode}){return <div className="toolbar"><label className="search-field"><Search size={14}/><input value={query} onChange={event=>onQuery(event.target.value)} placeholder={placeholder}/></label>{children}</div>;}

export function ClientsScreen(){
  const {data,createRecord}=useBusinessData();const [query,setQuery]=useState("");const [city,setCity]=useState("all");const [showForm,setShowForm]=useState(false);
  const filtered=data.clients.filter(client=>`${client.companyName} ${client.brandName} ${client.contactPerson}`.toLowerCase().includes(query.toLowerCase())&&(city==="all"||client.city===city));
  async function addClient(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await createRecord("clients",{id:crypto.randomUUID(),companyName:String(form.get("companyName")),brandName:String(form.get("brandName")),contactPerson:String(form.get("contactPerson")),mobile:String(form.get("mobile")),email:String(form.get("email")),city:String(form.get("city")),contractStatus:"active"});setShowForm(false);}
  return <><PageHeader title="Clients" description="Manage company master records and open a full page to edit each client." actions={<button className="button button--primary" onClick={()=>setShowForm(value=>!value)}><Plus size={14}/>New Client</button>}/>
    {showForm?<form className="card form-card" onSubmit={event=>void addClient(event)}><div className="form-grid">{[["companyName","Company Name"],["brandName","Brand Name"],["contactPerson","Contact Person"],["mobile","Mobile"],["email","Email"],["city","City"]].map(([name,label])=><label className="field" key={name}><span>{label}</span><input name={name} type={name==="email"?"email":"text"} required/></label>)}</div><div className="form-actions"><button type="button" className="button" onClick={()=>setShowForm(false)}>Cancel</button><button className="button button--primary">Save Client</button></div></form>:null}
    <section className="card"><Toolbar query={query} onQuery={setQuery} placeholder="Search company or brand..."><select className="select" value={city} onChange={event=>setCity(event.target.value)}><option value="all">All Cities</option>{[...new Set(data.clients.map(item=>item.city).filter(Boolean))].map(item=><option key={item}>{item}</option>)}</select></Toolbar><div className="table-wrap"><table className="data-table"><thead><tr><th>Company</th><th>Brand</th><th>Contact</th><th>Details</th><th>City</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.length?filtered.map(client=><tr key={client.id}><td>{client.companyName}</td><td>{client.brandName||"—"}</td><td>{client.contactPerson||"—"}</td><td>{client.mobile||"—"}<br/><small>{client.email}</small></td><td>{client.city||"—"}</td><td><StatusBadge value={client.contractStatus}/></td><td><Link className="icon-button" href={`${routes.editClient}?id=${encodeURIComponent(client.id)}`} title="Edit full client"><Edit3 size={15}/></Link></td></tr>):<EmptyTableRow columns={7}/>}</tbody></table></div></section>
  </>;
}

export function ProjectsScreen({status}:{status?:Project["status"]}){const {data}=useBusinessData();const [query,setQuery]=useState("");const source=status?data.projects.filter(item=>item.status===status):data.projects;const filtered=source.filter(item=>`${item.id} ${item.company} ${item.workDescription}`.toLowerCase().includes(query.toLowerCase()));const title=status==="in-progress"?"Ongoing Projects":status==="completed"?"Completed Projects":"Projects";return <><PageHeader title={title} description="Monitor projects; use the edit action for complete record changes."/><section className="card"><Toolbar query={query} onQuery={setQuery} placeholder="Search projects..."/><div className="table-wrap"><table className="data-table"><thead><tr><th>ID</th><th>Company</th><th>Store</th><th>Description</th><th>Value</th><th>Completion</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.length?filtered.map(project=><tr key={project.id}><td>{project.id}</td><td>{project.company}</td><td>{project.store}</td><td>{project.workDescription}</td><td>{money(project.value)}</td><td>{project.completion}%</td><td><StatusBadge value={project.status}/></td><td><Link className="icon-button" href={`${routes.editProject}?id=${encodeURIComponent(project.id)}`}><Edit3 size={15}/></Link></td></tr>):<EmptyTableRow columns={8}/>}</tbody></table></div></section></>;}

export function InvoicesScreen({pendingOnly=false}:{pendingOnly?:boolean}){
  const {data,updateInvoiceStatus,completeInvoicePayment}=useBusinessData();const [query,setQuery]=useState("");const [status,setStatus]=useState("all");const [modal,setModal]=useState(false);const [draft,setDraft]=useState<InvoiceImportDraft|null>(null);const [importing,setImporting]=useState(false);const [error,setError]=useState("");const input=useRef<HTMLInputElement|null>(null);
  const source=pendingOnly?data.invoices.filter(item=>["pending","partial","overdue"].includes(item.status)):data.invoices;const filtered=source.filter(item=>`${item.id} ${item.companyName} ${item.project}`.toLowerCase().includes(query.toLowerCase())&&(status==="all"||item.status===status));const total=source.reduce((sum,item)=>sum+item.amount,0);const received=source.reduce((sum,item)=>sum+item.received,0);
  async function change(id:string,next:string){if(next==="paid")await completeInvoicePayment(id);else await updateInvoiceStatus(id,next as Invoice["status"]);}
  async function importFile(file?:File){if(!file)return;setImporting(true);setError("");try{setDraft(await parseInvoiceDocument(file));setModal(true);}catch(e){setError(e instanceof Error?e.message:"Invoice import failed.");}finally{setImporting(false);}}
  async function exportPdf(invoice:Invoice){setError("");try{await exportInvoicePdf(invoice,data.company);}catch(e){setError(e instanceof Error?e.message:"Invoice export failed.");}}
  return <><PageHeader title={pendingOnly?"Pending Payments":"Invoices & Payments"} description={pendingOnly?"Follow up outstanding balances.":"Create invoices and use a full page for record editing."} actions={!pendingOnly?<><button className="button" disabled={importing} onClick={()=>input.current?.click()}>{importing?<LoaderCircle className="spin" size={14}/>:<FileUp size={14}/>}Import Excel / PDF</button><button className="button button--primary" onClick={()=>{setDraft(null);setModal(true);}}><Plus size={14}/>New Invoice</button></>:undefined}/>
    <input ref={input} className="file-input" type="file" accept=".pdf,.xlsx,.xls,.xlsm,.xlsb,.ods,.csv" onChange={event=>{const file=event.target.files?.[0];event.target.value="";void importFile(file);}}/>{error?<div className="form-message form-message--error">{error}</div>:null}
    <section className="metrics"><article className="metric-card card"><p>Total Invoiced</p><strong>{money(total)}</strong></article><article className="metric-card card"><p>Total Received</p><strong>{money(received)}</strong></article><article className="metric-card card"><p>Outstanding</p><strong>{money(total-received)}</strong></article></section>
    <section className="card"><Toolbar query={query} onQuery={setQuery} placeholder="Search invoice, company, or project..."><select className="select" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All Statuses</option><option value="pending">pending</option><option value="partial">partial</option><option value="paid">paid</option><option value="overdue">overdue</option></select></Toolbar><div className="table-wrap"><table className="data-table"><thead><tr><th>Company</th><th>Project</th><th>Invoice</th><th>Date</th><th>Amount</th><th>Received</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.length?filtered.map(invoice=><tr key={invoice.id}><td>{invoice.companyName}</td><td>{invoice.project||"—"}</td><td>{invoice.id}</td><td>{invoice.invoiceDate}</td><td>{money(invoice.amount)}</td><td>{money(invoice.received)}</td><td>{money(invoice.amount-invoice.received)}</td><td><select className="inline-select status-inline-select" value={invoice.status} onChange={event=>void change(invoice.id,event.target.value)}><option value="pending">pending</option><option value="partial">partial</option><option value="paid">paid</option><option value="overdue">overdue</option></select></td><td><div className="row-actions"><button className="icon-button" type="button" onClick={()=>void exportPdf(invoice)} title="Export ZATCA invoice PDF"><Download size={15}/></button><Link className="icon-button" href={`${routes.editInvoice}?id=${encodeURIComponent(invoice.id)}`} title="Edit full invoice"><Edit3 size={15}/></Link></div></td></tr>):<EmptyTableRow columns={9} message="No invoices found."/>}</tbody></table></div></section>
    {modal?<InvoiceDocumentModal draft={draft} onClose={()=>{setModal(false);setDraft(null);}}/>:null}
  </>;
}
